"""Gemini embedding client used by the RAG pipeline."""

import logging
import os
import time
from typing import List, Tuple


logger = logging.getLogger(__name__)

EMBEDDING_DIMENSION = 768
DEFAULT_EMBEDDING_MODEL = "gemini-embedding-001"


class EmbeddingServiceError(RuntimeError):
    """Raised when an embedding cannot be generated by Gemini."""


class GeminiEmbeddingPipeline:
    """Generate fixed-size Gemini embeddings for retrieval.

    The pgvector columns use 768 dimensions.  Requesting that size explicitly
    prevents a provider-side default change from corrupting writes to those
    columns.  Provider failures are deliberately surfaced: storing an all-zero
    vector makes unrelated inventory records appear equally relevant.
    """

    def __init__(self) -> None:
        self._client = None
        self._types = None
        self._initialized = False
        self.api_key = os.getenv("GEMINI_API_KEY", "").strip()
        self.model = os.getenv("GEMINI_EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)

        # Keep the application importable without AI credentials so health
        # checks and non-AI endpoints can run. Actual embedding requests fail
        # with an explicit, provider-safe error below.

    def _ensure_initialized(self) -> None:
        """Lazily create the current Google Gen AI SDK client."""
        if self._initialized:
            return

        if not self.api_key:
            raise EmbeddingServiceError(
                "Gemini embeddings are unavailable. Configure GEMINI_API_KEY to enable RAG."
            )

        try:
            from google import genai
            from google.genai import types

            self._client = genai.Client(api_key=self.api_key)
            self._types = types
            self._initialized = True
            logger.info("Gemini embedding client initialized (%s, %sD)", self.model, EMBEDDING_DIMENSION)
        except ImportError as exc:
            raise ImportError(
                "google-genai is not installed. Run: pip install -r requirements.txt"
            ) from exc
        except Exception as exc:
            raise EmbeddingServiceError("Unable to initialize the Gemini embedding client.") from exc

    def _embed(self, contents: str | List[str], task_type: str) -> List[List[float]]:
        """Embed one or more non-empty texts and validate the provider response."""
        self._ensure_initialized()

        try:
            result = self._client.models.embed_content(
                model=self.model,
                contents=contents,
                config=self._types.EmbedContentConfig(
                    task_type=task_type,
                    output_dimensionality=EMBEDDING_DIMENSION,
                ),
            )
            embeddings = [list(embedding.values) for embedding in result.embeddings]
        except Exception as exc:
            logger.error("Gemini embedding request failed: %s", exc)
            raise EmbeddingServiceError(
                "Gemini embeddings are unavailable. Check GEMINI_API_KEY and Gemini API access."
            ) from exc

        expected_count = 1 if isinstance(contents, str) else len(contents)
        if len(embeddings) != expected_count:
            raise EmbeddingServiceError(
                f"Gemini returned {len(embeddings)} embeddings for {expected_count} inputs."
            )
        if any(len(embedding) != EMBEDDING_DIMENSION for embedding in embeddings):
            raise EmbeddingServiceError(
                f"Gemini returned an embedding with a dimension other than {EMBEDDING_DIMENSION}."
            )

        return embeddings

    def generate_embedding(self, text: str) -> List[float]:
        """Generate a retrieval-query embedding for ``text``."""
        if not isinstance(text, str) or not text.strip():
            raise ValueError("Embedding text must be a non-empty string.")

        start = time.perf_counter()
        embedding = self._embed(text, task_type="RETRIEVAL_QUERY")[0]
        logger.debug("Generated embedding in %.2fms", (time.perf_counter() - start) * 1000)
        return embedding

    def generate_document_embedding(self, text: str) -> List[float]:
        """Generate a document embedding for persisted retrieval records."""
        if not isinstance(text, str) or not text.strip():
            raise ValueError("Embedding text must be a non-empty string.")
        start = time.perf_counter()
        embedding = self._embed(text, task_type="RETRIEVAL_DOCUMENT")[0]
        logger.debug("Generated document embedding in %.2fms", (time.perf_counter() - start) * 1000)
        return embedding

    def generate_embeddings_batch(self, texts: List[str]) -> List[List[float]]:
        """Generate retrieval-document embeddings for a batch of inventory texts."""
        if not texts:
            return []
        if any(not isinstance(text, str) or not text.strip() for text in texts):
            raise ValueError("Every embedding text must be a non-empty string.")

        # The synchronous API supports a list of contents.  Keep batches modest
        # so a single request cannot exceed the provider's input limit.
        batch_size = 100
        embeddings: List[List[float]] = []
        for start in range(0, len(texts), batch_size):
            embeddings.extend(
                self._embed(texts[start : start + batch_size], task_type="RETRIEVAL_DOCUMENT")
            )
        logger.info("Generated %s document embeddings", len(embeddings))
        return embeddings

    def generate_query_embedding(self, query: str) -> Tuple[List[float], float]:
        """Generate a query embedding and return the elapsed time in seconds."""
        start = time.perf_counter()
        return self.generate_embedding(query), time.perf_counter() - start

    @property
    def dimension(self) -> int:
        return EMBEDDING_DIMENSION

    def get_info(self) -> dict:
        """Return non-sensitive runtime metadata for diagnostics."""
        return {
            "provider": "gemini",
            "sdk": "google-genai",
            "model": self.model,
            "dimension": EMBEDDING_DIMENSION,
            "initialized": self._initialized,
            "api_key_configured": bool(self.api_key),
        }


embedding_pipeline = GeminiEmbeddingPipeline()
