import '../models/item.dart';

// The FULL list from your original app - ALL PRICES SET TO 0.0
final List<Item> masterInventoryList = [
  // Anaaj (Grains)
  Item(
      id: '101',
      names: ['Chawal', 'Rice', 'चावल', 'तांदूळ'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '102',
      names: ['Basmati Chawal', 'Basmati Rice', 'बासमती चावल'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '103',
      names: ['Gehun', 'Wheat', 'गेहूँ', 'गहू'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '104',
      names: ['Bajra', 'Pearl Millet', 'बाजरा', 'बाजरी'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '105',
      names: ['Jowar', 'Sorghum', 'ज्वार'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '106',
      names: ['Ragi', 'Nachni', 'Finger millet'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '107',
      names: ['Makka', 'Corn grain', 'मक्का'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '108',
      names: ['Poha', 'Flattened rice', 'पोहा'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '109',
      names: ['Bhagar', 'Varai', 'Upvas rice'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '110',
      names: ['Sabudana', 'Tapioca Pearls', 'साबूदाना'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '111',
      names: ['Suji', 'Rawa', 'Semolina'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),
  Item(
      id: '112',
      names: ['Daliya', 'Broken Wheat', 'दलिया'],
      price: 0.0,
      unit: 'kg',
      category: 'Anaaj'),

  // Atta (Flour)
  Item(
      id: '201',
      names: ['Gehun ka Atta', 'Wheat Flour', 'आटा'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '202',
      names: ['Maida', 'Refined flour', 'मैदा'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '203',
      names: ['Besan', 'Gram Flour', 'बेसन'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '204',
      names: ['Ragi Atta', 'Nachni flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '205',
      names: ['Jowar Atta', 'Sorghum flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '206',
      names: ['Bajra Atta', 'Millet flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '207',
      names: ['Rice Flour', 'Chawal ka atta'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),
  Item(
      id: '208',
      names: ['Makki ka Atta', 'Corn flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Atta'),

  // Dal (Pulses)
  Item(
      id: '301',
      names: ['Toor Dal', 'Arhar Dal', 'Pigeon pea'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '302',
      names: ['Moong Dal', 'Split green gram'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '303',
      names: ['Moong Sabut', 'Whole green gram'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '304',
      names: ['Chana Dal', 'Bengal gram'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '305',
      names: ['Kala Chana', 'Black chickpea'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '306',
      names: ['Kabuli Chana', 'White chickpea', 'छोले'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '307',
      names: ['Masoor Dal', 'Red lentil'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '308',
      names: ['Urad Dal', 'Black gram'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '309',
      names: ['Rajma Lal', 'Red kidney beans'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '310',
      names: ['Rajma Chitra', 'Speckled kidney beans'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '311',
      names: ['Matki', 'Moth', 'Dew beans'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '312',
      names: ['Kulthi', 'Horse gram'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),
  Item(
      id: '313',
      names: ['Lobiya', 'Black eyed beans'],
      price: 0.0,
      unit: 'kg',
      category: 'Dal'),

  // Oils (Tel)
  Item(
      id: '401',
      names: ['Sunflower Oil', 'Surajmukhi tel'],
      price: 0.0,
      unit: 'litre',
      category: 'Tel'),
  Item(
      id: '402',
      names: ['Mustard Oil', 'Sarson tel'],
      price: 0.0,
      unit: 'litre',
      category: 'Tel'),
  Item(
      id: '403',
      names: ['Groundnut Oil', 'Mungfali oil'],
      price: 0.0,
      unit: 'litre',
      category: 'Tel'),
  Item(
      id: '404',
      names: ['Coconut Oil', 'Nariyal tel'],
      price: 0.0,
      unit: 'litre',
      category: 'Tel'),
  Item(
      id: '405',
      names: ['Soybean Oil', 'Soya oil'],
      price: 0.0,
      unit: 'litre',
      category: 'Tel'),

  // Spices (Masale)
  Item(
      id: '501',
      names: ['Haldi', 'Turmeric'],
      price: 0.0,
      unit: 'kg',
      category: 'Masale'),
  Item(
      id: '502',
      names: ['Mirch Powder', 'Red chilli powder'],
      price: 0.0,
      unit: 'kg',
      category: 'Masale'),
  Item(
      id: '503',
      names: ['Dhaniya Powder', 'Coriander powder'],
      price: 0.0,
      unit: 'kg',
      category: 'Masale'),
  Item(
      id: '504',
      names: ['Jeera', 'Cumin'],
      price: 0.0,
      unit: 'kg',
      category: 'Masale'),
  Item(
      id: '505',
      names: ['Rai', 'Sarson'],
      price: 0.0,
      unit: 'kg',
      category: 'Masale'),
  Item(
      id: '506',
      names: ['Ajwain', 'Carom seeds'],
      price: 0.0,
      unit: '100g',
      category: 'Masale'),
  Item(
      id: '507',
      names: ['Elaichi', 'Cardamom'],
      price: 0.0,
      unit: '100g',
      category: 'Masale'),
  Item(
      id: '508',
      names: ['Tej Patta', 'Bay leaf'],
      price: 0.0,
      unit: '50g',
      category: 'Masale'),
  Item(
      id: '509',
      names: ['Dalchini', 'Cinnamon'],
      price: 0.0,
      unit: '100g',
      category: 'Masale'),
  Item(
      id: '510',
      names: ['Kalimirch', 'Black pepper'],
      price: 0.0,
      unit: '100g',
      category: 'Masale'),
  Item(
      id: '511',
      names: ['Hing', 'Asafoetida'],
      price: 0.0,
      unit: '50g',
      category: 'Masale'),

  // Dry Fruits
  Item(
      id: '601',
      names: ['Badam', 'Almonds'],
      price: 0.0,
      unit: 'kg',
      category: 'Dry Fruits'),
  Item(
      id: '602',
      names: ['Kaju', 'Cashews'],
      price: 0.0,
      unit: 'kg',
      category: 'Dry Fruits'),
  Item(
      id: '603',
      names: ['Pista', 'Pistachios'],
      price: 0.0,
      unit: 'kg',
      category: 'Dry Fruits'),
  Item(
      id: '604',
      names: ['Kishmish', 'Raisins'],
      price: 0.0,
      unit: 'kg',
      category: 'Dry Fruits'),
  Item(
      id: '605',
      names: ['Khajoor', 'Dates'],
      price: 0.0,
      unit: 'kg',
      category: 'Dry Fruits'),

  // Upvas
  Item(
      id: '701',
      names: ['Bhagar', 'Varai rice'],
      price: 0.0,
      unit: 'kg',
      category: 'Upvas'),
  Item(
      id: '702',
      names: ['Sabudana', 'Tapioca'],
      price: 0.0,
      unit: 'kg',
      category: 'Upvas'),
  Item(
      id: '703',
      names: ['Singhada Atta', 'Water chestnut flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Upvas'),
  Item(
      id: '704',
      names: ['Rajgira Atta', 'Amaranth flour'],
      price: 0.0,
      unit: 'kg',
      category: 'Upvas'),
  Item(
      id: '705',
      names: ['Sendha Namak', 'Rock salt'],
      price: 0.0,
      unit: 'kg',
      category: 'Upvas'),

  // Other / Fast Food
  Item(
      id: '801',
      names: ['Chini', 'Sugar'],
      price: 0.0,
      unit: 'kg',
      category: 'Other'),
  Item(
      id: '802',
      names: ['Tata Namak', 'Iodised Salt'],
      price: 0.0,
      unit: 'kg',
      category: 'Other'),
  Item(
      id: '803',
      names: ['Sendha Namak', 'Rock Salt'],
      price: 0.0,
      unit: 'kg',
      category: 'Other'),
  Item(
      id: '804',
      names: ['Gur', 'Jaggery'],
      price: 0.0,
      unit: 'kg',
      category: 'Other'),
  Item(
      id: '805',
      names: ['Samosa'],
      price: 0.0,
      unit: 'plate',
      category: 'Fast Food'),
  Item(
      id: '806',
      names: ['Namkeen'],
      price: 0.0,
      unit: '250gm',
      category: 'Snacks'),
  Item(
      id: '807',
      names: ['Tea', 'Chai'],
      price: 0.0,
      unit: 'cup',
      category: 'Beverages'),
  Item(
      id: '808',
      names: ['Coffee'],
      price: 0.0,
      unit: 'cup',
      category: 'Beverages'),
];

// Frequent List (Shortcuts) - Pre-populated with Indian market prices
final List<Item> masterFrequentList = [
  // Pizza Category
  Item(id: 'pizza_1', names: ['Margherita Pizza'], price: 150, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_2', names: ['Paneer Pizza'], price: 180, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_3', names: ['Corn Pizza'], price: 160, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_4', names: ['Onion Pizza'], price: 140, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_5', names: ['Capsicum Pizza'], price: 170, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_6', names: ['Mushroom Pizza'], price: 190, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_7', names: ['Cheese Pizza'], price: 200, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_8', names: ['Veg Supreme Pizza'], price: 220, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_9', names: ['Deluxe Pizza'], price: 210, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_10', names: ['Farm Fresh Pizza'], price: 195, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_11', names: ['Mexican Pizza'], price: 230, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_12', names: ['Italian Pizza'], price: 240, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_13', names: ['BBQ Pizza'], price: 250, unit: 'plate', category: 'Pizza'),
  Item(id: 'pizza_14', names: ['Spicy Veg Pizza'], price: 225, unit: 'plate', category: 'Pizza'),

  // Burger Category
  Item(id: 'burger_1', names: ['Veg Burger'], price: 50, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_2', names: ['Cheese Burger'], price: 70, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_3', names: ['Paneer Burger'], price: 80, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_4', names: ['Aloo Tikki Burger'], price: 60, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_5', names: ['Corn Burger'], price: 65, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_6', names: ['Mushroom Burger'], price: 85, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_7', names: ['Veg Cheese Burger'], price: 90, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_8', names: ['Spicy Veg Burger'], price: 75, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_9', names: ['Crispy Burger'], price: 72, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_10', names: ['Deluxe Burger'], price: 95, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_11', names: ['Mexican Burger'], price: 88, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_12', names: ['Jumbo Burger'], price: 100, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_13', names: ['Tandoori Burger'], price: 92, unit: 'pics', category: 'Burger'),
  Item(id: 'burger_14', names: ['Double Patty Burger'], price: 110, unit: 'pics', category: 'Burger'),

  // Snacks Category
  Item(id: 'snacks_1', names: ['Samosa'], price: 15, unit: 'pics', category: 'Snacks'),
  Item(id: 'snacks_2', names: ['Kachori'], price: 20, unit: 'pics', category: 'Snacks'),
  Item(id: 'snacks_3', names: ['Vada Pav'], price: 25, unit: 'pics', category: 'Snacks'),
  Item(id: 'snacks_4', names: ['Pav Bhaji'], price: 60, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_5', names: ['Pakora'], price: 40, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_6', names: ['Spring Roll'], price: 50, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_7', names: ['French Fries'], price: 60, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_8', names: ['Paneer Pakora'], price: 70, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_9', names: ['Cutlet'], price: 30, unit: 'pics', category: 'Snacks'),
  Item(id: 'snacks_10', names: ['Dahi Puri'], price: 35, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_11', names: ['Bhel Puri'], price: 30, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_12', names: ['Sev Puri'], price: 40, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_13', names: ['Ragda Pattice'], price: 50, unit: 'plate', category: 'Snacks'),
  Item(id: 'snacks_14', names: ['Aloo Chaat'], price: 45, unit: 'plate', category: 'Snacks'),

  // Noodles Category
  Item(id: 'noodles_1', names: ['Veg Noodles'], price: 80, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_2', names: ['Hakka Noodles'], price: 90, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_3', names: ['Schezwan Noodles'], price: 100, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_4', names: ['Chilli Garlic Noodles'], price: 95, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_5', names: ['Singapore Noodles'], price: 110, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_6', names: ['Paneer Noodles'], price: 120, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_7', names: ['Mushroom Noodles'], price: 115, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_8', names: ['Triple Schezwan Noodles'], price: 130, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_9', names: ['Hong Kong Noodles'], price: 125, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_10', names: ['American Chopsuey'], price: 140, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_11', names: ['Thai Noodles'], price: 135, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_12', names: ['Korean Noodles'], price: 145, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_13', names: ['Crispy Noodles'], price: 138, unit: 'plate', category: 'Noodles'),
  Item(id: 'noodles_14', names: ['Burnt Garlic Noodles'], price: 128, unit: 'plate', category: 'Noodles'),

  // Cakes Category
  Item(id: 'cakes_1', names: ['Chocolate Cake'], price: 400, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_2', names: ['Vanilla Cake'], price: 350, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_3', names: ['Black Forest Cake'], price: 450, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_4', names: ['Pineapple Cake'], price: 380, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_5', names: ['Butterscotch Cake'], price: 420, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_6', names: ['Red Velvet Cake'], price: 500, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_7', names: ['Strawberry Cake'], price: 430, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_8', names: ['Fruit Cake'], price: 460, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_9', names: ['Truffle Cake'], price: 480, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_10', names: ['White Forest Cake'], price: 440, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_11', names: ['Blueberry Cake'], price: 470, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_12', names: ['Mango Cake'], price: 410, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_13', names: ['Coffee Cake'], price: 390, unit: 'kg', category: 'Cakes'),
  Item(id: 'cakes_14', names: ['Caramel Cake'], price: 460, unit: 'kg', category: 'Cakes'),

  // Beverages Category
  Item(id: 'beverages_1', names: ['Cold Coffee'], price: 60, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_2', names: ['Hot Coffee'], price: 40, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_3', names: ['Tea'], price: 20, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_4', names: ['Masala Tea'], price: 25, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_5', names: ['Mango Shake'], price: 70, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_6', names: ['Chocolate Shake'], price: 80, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_7', names: ['Fresh Lime Soda'], price: 40, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_8', names: ['Lassi'], price: 50, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_9', names: ['Banana Shake'], price: 65, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_10', names: ['Strawberry Shake'], price: 75, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_11', names: ['Green Tea'], price: 30, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_12', names: ['Lemonade'], price: 35, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_13', names: ['Iced Tea'], price: 45, unit: 'pics', category: 'Beverages'),
  Item(id: 'beverages_14', names: ['Mojito'], price: 55, unit: 'pics', category: 'Beverages'),

  // Ice Cream Category
  Item(id: 'icecream_1', names: ['Vanilla Ice Cream'], price: 40, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_2', names: ['Chocolate Ice Cream'], price: 50, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_3', names: ['Strawberry Ice Cream'], price: 45, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_4', names: ['Butterscotch Ice Cream'], price: 55, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_5', names: ['Mango Ice Cream'], price: 60, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_6', names: ['Kulfi'], price: 30, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_7', names: ['Sundae'], price: 80, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_8', names: ['Ice Cream Sandwich'], price: 35, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_9', names: ['Pista Ice Cream'], price: 65, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_10', names: ['Cassata'], price: 70, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_11', names: ['Black Current'], price: 55, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_12', names: ['Tutti Frutti'], price: 50, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_13', names: ['Choco Chip'], price: 62, unit: 'pics', category: 'Ice Cream'),
  Item(id: 'icecream_14', names: ['Mint Chocolate'], price: 68, unit: 'pics', category: 'Ice Cream'),

  // Sandwiches Category
  Item(id: 'sandwich_1', names: ['Veg Sandwich'], price: 40, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_2', names: ['Cheese Sandwich'], price: 50, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_3', names: ['Grilled Sandwich'], price: 60, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_4', names: ['Paneer Sandwich'], price: 70, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_5', names: ['Corn Sandwich'], price: 55, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_6', names: ['Bombay Sandwich'], price: 65, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_7', names: ['Club Sandwich'], price: 80, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_8', names: ['Cheese Chilli Sandwich'], price: 75, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_9', names: ['Masala Sandwich'], price: 45, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_10', names: ['Mayo Sandwich'], price: 52, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_11', names: ['Jumbo Sandwich'], price: 85, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_12', names: ['Deluxe Sandwich'], price: 90, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_13', names: ['Tandoori Sandwich'], price: 78, unit: 'pics', category: 'Sandwiches'),
  Item(id: 'sandwich_14', names: ['Aloo Tikki Sandwich'], price: 58, unit: 'pics', category: 'Sandwiches'),

  // Rolls Category
  Item(id: 'rolls_1', names: ['Veg Roll'], price: 50, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_2', names: ['Paneer Roll'], price: 70, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_3', names: ['Cheese Roll'], price: 60, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_4', names: ['Schezwan Roll'], price: 65, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_5', names: ['Aloo Roll'], price: 45, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_6', names: ['Mushroom Roll'], price: 75, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_7', names: ['Spring Roll'], price: 55, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_8', names: ['Paneer Tikka Roll'], price: 85, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_9', names: ['Corn Roll'], price: 58, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_10', names: ['Mixed Veg Roll'], price: 68, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_11', names: ['Crispy Roll'], price: 72, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_12', names: ['Mexican Roll'], price: 78, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_13', names: ['Tandoori Roll'], price: 80, unit: 'pics', category: 'Rolls'),
  Item(id: 'rolls_14', names: ['Deluxe Roll'], price: 90, unit: 'pics', category: 'Rolls'),

  // Chinese Category
  Item(id: 'chinese_1', names: ['Veg Fried Rice'], price: 90, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_2', names: ['Schezwan Fried Rice'], price: 100, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_3', names: ['Veg Manchurian'], price: 110, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_4', names: ['Chilli Paneer'], price: 130, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_5', names: ['Veg Chowmein'], price: 85, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_6', names: ['Spring Roll'], price: 70, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_7', names: ['Paneer Manchurian'], price: 140, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_8', names: ['Veg Momos'], price: 60, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_9', names: ['Chilli Mushroom'], price: 120, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_10', names: ['Paneer Chowmein'], price: 105, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_11', names: ['Mixed Fried Rice'], price: 95, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_12', names: ['Garlic Fried Rice'], price: 92, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_13', names: ['Paneer Momos'], price: 75, unit: 'plate', category: 'Chinese'),
  Item(id: 'chinese_14', names: ['Crispy Veg'], price: 125, unit: 'plate', category: 'Chinese'),
];


